name: Test and Run Script

on:
  push:
    branches:
      - main

jobs:
  test_and_run:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest tests.test_apiservice

      - name: Run Script if tests pass
        run: python main.py

